/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AlgorithmInput { 
    inputList?: Array<AlgorithmInput>;
    multiplicity?: AlgorithmInput.MultiplicityEnum;
}
export namespace AlgorithmInput {
    export type MultiplicityEnum = 'SINGLE' | 'ARRAY';
    export const MultiplicityEnum = {
        SINGLE: 'SINGLE' as MultiplicityEnum,
        ARRAY: 'ARRAY' as MultiplicityEnum
    };
}
