/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AlgorithmOutputField { 
    id?: number;
    name?: string;
    description?: string;
    type?: AlgorithmOutputField.TypeEnum;
    multiplicity?: AlgorithmOutputField.MultiplicityEnum;
}
export namespace AlgorithmOutputField {
    export type TypeEnum = 'INTEGER' | 'LONG' | 'DOUBLE' | 'FLOAT' | 'TEXT' | 'BYTE';
    export const TypeEnum = {
        INTEGER: 'INTEGER' as TypeEnum,
        LONG: 'LONG' as TypeEnum,
        DOUBLE: 'DOUBLE' as TypeEnum,
        FLOAT: 'FLOAT' as TypeEnum,
        TEXT: 'TEXT' as TypeEnum,
        BYTE: 'BYTE' as TypeEnum
    };
    export type MultiplicityEnum = 'SINGLE' | 'ARRAY' | 'MATRIX';
    export const MultiplicityEnum = {
        SINGLE: 'SINGLE' as MultiplicityEnum,
        ARRAY: 'ARRAY' as MultiplicityEnum,
        MATRIX: 'MATRIX' as MultiplicityEnum
    };
}
