/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HDevice } from './hDevice';
import { HProject } from './hProject';
import { HyperIoTBaseEntity } from './hyperIoTBaseEntity';


export interface Area { 
    id?: number;
    categoryIds?: Array<number>;
    tagIds?: Array<number>;
    name: string;
    description: string;
    project: HProject;
    devices?: Array<HDevice>;
    parentArea?: Area;
    innerArea?: Array<Area>;
    parent?: HyperIoTBaseEntity;
    systemApiClassName?: string;
    resourceName?: string;
}
