/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssetCategory } from './assetCategory';
import { HyperIoTBaseEntity } from './hyperIoTBaseEntity';


export interface AssetCategoryResource { 
    id?: number;
    categoryIds?: Array<number>;
    tagIds?: Array<number>;
    resourceName: string;
    resourceId?: number;
    category?: AssetCategory;
    systemApiClassName?: string;
    parent?: HyperIoTBaseEntity;
}
