/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DataFlavor { 
    mimeType?: string;
    humanPresentableName?: string;
    primaryType?: string;
    subType?: string;
    defaultRepresentationClassAsString?: string;
    flavorJavaFileListType?: boolean;
    flavorRemoteObjectType?: boolean;
    flavorSerializedObjectType?: boolean;
    flavorTextType?: boolean;
    mimeTypeSerializedObject?: boolean;
    representationClassByteBuffer?: boolean;
    representationClassCharBuffer?: boolean;
    representationClassInputStream?: boolean;
    representationClassReader?: boolean;
    representationClassRemote?: boolean;
    representationClassSerializable?: boolean;
}
