/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HProject } from './hProject';
import { HyperIoTBaseEntity } from './hyperIoTBaseEntity';
import { HyperIoTRole } from './hyperIoTRole';


export interface HDevice { 
    id?: number;
    categoryIds?: Array<number>;
    tagIds?: Array<number>;
    deviceName: string;
    password?: string;
    passwordConfirm?: string;
    brand: string;
    model: string;
    firmwareVersion: string;
    softwareVersion: string;
    description: string;
    project: HProject;
    admin?: boolean;
    active?: boolean;
    screenName?: string;
    roles?: Array<HyperIoTRole>;
    parent?: HyperIoTBaseEntity;
    systemApiClassName?: string;
    resourceName?: string;
}
