/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HyperIoTBaseEntity } from './hyperIoTBaseEntity';
import { Role } from './role';


export interface HUser { 
    id?: number;
    categoryIds?: Array<number>;
    tagIds?: Array<number>;
    name: string;
    lastname: string;
    username: string;
    password?: string;
    admin?: boolean;
    passwordConfirm?: string;
    passwordResetCode?: string;
    email: string;
    roles?: Array<Role>;
    active?: boolean;
    activateCode?: string;
    screenName?: string;
    systemApiClassName?: string;
    parent?: HyperIoTBaseEntity;
    resourceName?: string;
}
