/**
 * HyperIoT Company
 * HyperIoT Company API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HyperIoTRole } from './hyperIoTRole';


export interface HyperIoTUser { 
    email?: string;
    roles?: Array<HyperIoTRole>;
    username?: string;
    name?: string;
    lastname?: string;
    id?: number;
    entityVersion?: number;
    categoryIds?: Array<number>;
    entityCreateDate?: Date;
    tagIds?: Array<number>;
    systemApiClassName?: string;
    resourceName?: string;
    screenName?: string;
}
