/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IteratorEntryStringJsonNode } from './iteratorEntryStringJsonNode';
import { IteratorJsonNode } from './iteratorJsonNode';
import { IteratorString } from './iteratorString';
import { Number } from './number';


export interface JsonNode { 
    numberType?: JsonNode.NumberTypeEnum;
    bigIntegerValue?: number;
    decimalValue?: number;
    doubleValue?: number;
    containerNode?: boolean;
    missingNode?: boolean;
    integralNumber?: boolean;
    floatingPointNumber?: boolean;
    _long?: boolean;
    _double?: boolean;
    bigDecimal?: boolean;
    bigInteger?: boolean;
    pojo?: boolean;
    valueNode?: boolean;
    numberValue?: Number;
    booleanValue?: boolean;
    binaryValue?: Array<string>;
    valueAsInt?: number;
    valueAsBoolean?: boolean;
    valueAsText?: string;
    intValue?: number;
    longValue?: number;
    fieldNames?: IteratorString;
    elements?: IteratorJsonNode;
    textValue?: string;
    valueAsLong?: number;
    valueAsDouble?: number;
    binary?: boolean;
    textual?: boolean;
    _boolean?: boolean;
    _int?: boolean;
    number?: boolean;
    object?: boolean;
    array?: boolean;
    fields?: IteratorEntryStringJsonNode;
    _null?: boolean;
}
export namespace JsonNode {
    export type NumberTypeEnum = 'INT' | 'LONG' | 'BIG_INTEGER' | 'FLOAT' | 'DOUBLE' | 'BIG_DECIMAL';
    export const NumberTypeEnum = {
        INT: 'INT' as NumberTypeEnum,
        LONG: 'LONG' as NumberTypeEnum,
        BIGINTEGER: 'BIG_INTEGER' as NumberTypeEnum,
        FLOAT: 'FLOAT' as NumberTypeEnum,
        DOUBLE: 'DOUBLE' as NumberTypeEnum,
        BIGDECIMAL: 'BIG_DECIMAL' as NumberTypeEnum
    };
}
