/**
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Field } from './field';
import { JsonNode } from './jsonNode';
import { LogicalType } from './logicalType';


export interface Schema { 
    props?: { [key: string]: string; };
    type?: Schema.TypeEnum;
    logicalType?: LogicalType;
    elementType?: Schema;
    aliases?: Array<string>;
    fields?: Array<Field>;
    fullName?: string;
    valueType?: Schema;
    enumSymbols?: Array<string>;
    doc?: string;
    fixedSize?: number;
    name?: string;
    error?: boolean;
    types?: Array<Schema>;
    namespace?: string;
    jsonProps?: { [key: string]: JsonNode; };
    objectProps?: { [key: string]: any; };
}
export namespace Schema {
    export type TypeEnum = 'RECORD' | 'ENUM' | 'ARRAY' | 'MAP' | 'UNION' | 'FIXED' | 'STRING' | 'BYTES' | 'INT' | 'LONG' | 'FLOAT' | 'DOUBLE' | 'BOOLEAN' | 'NULL';
    export const TypeEnum = {
        RECORD: 'RECORD' as TypeEnum,
        ENUM: 'ENUM' as TypeEnum,
        ARRAY: 'ARRAY' as TypeEnum,
        MAP: 'MAP' as TypeEnum,
        UNION: 'UNION' as TypeEnum,
        FIXED: 'FIXED' as TypeEnum,
        STRING: 'STRING' as TypeEnum,
        BYTES: 'BYTES' as TypeEnum,
        INT: 'INT' as TypeEnum,
        LONG: 'LONG' as TypeEnum,
        FLOAT: 'FLOAT' as TypeEnum,
        DOUBLE: 'DOUBLE' as TypeEnum,
        BOOLEAN: 'BOOLEAN' as TypeEnum,
        NULL: 'NULL' as TypeEnum
    };
}
