/**
 * HyperIoT Rule
 * HyperIoT Rule API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: users@acsoftware.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HDevice } from './hDevice';
import { HPacketField } from './hPacketField';


export interface HPacket { 
    id?: number;
    categoryIds?: Array<number>;
    tagIds?: Array<number>;
    name: string;
    type: HPacket.TypeEnum;
    format: HPacket.FormatEnum;
    serialization: HPacket.SerializationEnum;
    device: HDevice;
    version: string;
    fields?: Array<HPacketField>;
    valid?: boolean;
    resourceName?: string;
}
export namespace HPacket {
    export type TypeEnum = 'INPUT' | 'OUTPUT' | 'IO';
    export const TypeEnum = {
        INPUT: 'INPUT' as TypeEnum,
        OUTPUT: 'OUTPUT' as TypeEnum,
        IO: 'IO' as TypeEnum
    };
    export type FormatEnum = 'JSON' | 'XML' | 'CSV';
    export const FormatEnum = {
        JSON: 'JSON' as FormatEnum,
        XML: 'XML' as FormatEnum,
        CSV: 'CSV' as FormatEnum
    };
    export type SerializationEnum = 'AVRO' | 'NONE';
    export const SerializationEnum = {
        AVRO: 'AVRO' as SerializationEnum,
        NONE: 'NONE' as SerializationEnum
    };
}
